#!/usr/bin/env bash

# Install HAProxy
sudo apt-get update
sudo apt-get install -y haproxy

# Configure HAProxy
sudo sed -i 's/^\(.*listen.*\)80/\18080/' /etc/haproxy/haproxy.cfg
sudo sed -i '/^backend.*http/ a \ \ \ \ balance roundrobin\n\ \ \ \ server 163169-web-01 163169-web-01:80 check\n\ \ \ \ server 163169-web-02 163169-web-02:80 check' /etc/haproxy/haproxy.cfg

# Enable HAProxy service
sudo systemctl enable haproxy

# Restart HAProxy service
sudo systemctl restart haproxy
